# Generated by Django 3.1.1 on 2020-09-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200906_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/assets/img')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=50)),
            ],
        ),
    ]
