# Generated by Django 3.1.1 on 2020-09-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_checkout_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='city',
            new_name='district',
        ),
    ]
