# Generated by Django 3.1.1 on 2020-09-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200919_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phonenumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
